/**
 * NEXUS - Status Output Generator
 * Produces NEXUS_STATUS.md in founder zero-think format
 */

import * as fs from 'fs';
import * as path from 'path';
import { NexusStatus, NexusState } from './types';
import { nexusConfig } from './config';

/**
 * Write status to JSON file
 */
export function writeNexusJson(status: NexusStatus): void {
    const outputPath = path.resolve(process.cwd(), nexusConfig.output.statusFile);
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(outputPath, JSON.stringify(status, null, 2), 'utf-8');
    console.log(`📄 NEXUS JSON: ${outputPath}`);
}

/**
 * State emoji map
 */
const STATE_EMOJI: Record<NexusState, string> = {
    STABLE_AND_PRODUCING: '🟢',
    STABLE_BUT_IDLE: '🟡',
    MISALIGNED_BUILDING_NO_DISTRIBUTION: '🟠',
    BROKEN_PLATFORM: '🔴',
    BROKEN_OUTPUT_PIPELINE: '🔴',
    RISKY_DRIFT: '🟣',
};

/**
 * Write NEXUS_STATUS.md - THE founder document
 */
export function writeNexusMarkdown(status: NexusStatus): void {
    const outputPath = path.resolve(process.cwd(), nexusConfig.output.statusMarkdown);
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    let md = `# NEXUS — GG LOOP Operating Brain

**Last Check:** ${status.timestamp.toISOString()}
${status.inSafeMode ? '\n⚠️ **SAFE MODE ACTIVE** — Innovation paused, focus on restore\n' : ''}
---

## ${STATE_EMOJI[status.state]} STATE: ${status.state.replace(/_/g, ' ')}

${status.reason}

`;

    // Auto actions
    md += `---\n\n## 🤖 AUTO_ACTIONS (What NEXUS is doing)\n\n`;
    if (status.autoActions.length === 0) {
        md += `No auto-actions running.\n\n`;
    } else {
        for (const action of status.autoActions) {
            const icon = action.status === 'running' ? '▶️' : action.status === 'completed' ? '✅' : '⏸️';
            md += `- ${icon} ${action.description}\n`;
        }
        md += `\n`;
    }

    // Next action (ONLY if required)
    md += `---\n\n## 🎯 NEXT_ACTION (Founder required only if shown)\n\n`;
    if (status.nextAction) {
        md += `**${status.nextAction}**\n\n`;
    } else {
        md += `*No founder action required. NEXUS is handling everything.*\n\n`;
    }

    // Prevention upgrades
    md += `---\n\n## 🛡️ PREVENTION_UPGRADES (2 required)\n\n`;
    for (const upgrade of status.preventionUpgrades) {
        md += `### ${upgrade.type === 'leverage' ? '⚡' : '🔧'} ${upgrade.title}\n`;
        md += `**Type:** ${upgrade.type} | **Effort:** ${upgrade.effort} | **Impact:** ${upgrade.impact}\n`;
        md += `${upgrade.description}\n\n`;
    }

    // Innovation (MANDATORY every run)
    md += `---\n\n## 💡 INNOVATION (Mandatory this run)\n\n`;
    md += `### ⚡ LEVERAGE UPGRADE: ${status.innovation.leverageUpgrade.title}\n`;
    md += `${status.innovation.leverageUpgrade.description}\n\n`;
    md += `### 🔧 EFFICIENCY UPGRADE: ${status.innovation.efficiencyUpgrade.title}\n`;
    md += `${status.innovation.efficiencyUpgrade.description}\n\n`;

    // Hardware bridge concept
    md += `---\n\n## 🔌 HARDWARE BRIDGE (Design Only)\n\n`;
    const hw = nexusConfig.hardwareBridge;
    md += `**${hw.name}:** ${hw.description}\n`;
    md += `**Leverage Ratio:** ${hw.leverageRatio}\n`;
    md += `**Notes:** ${hw.implementationNotes}\n\n`;

    md += `---\n\n*NEXUS run #${status.runCount} — Auto-generated by GG LOOP Operating Brain*\n`;

    fs.writeFileSync(outputPath, md, 'utf-8');
    console.log(`📄 NEXUS MD: ${outputPath}`);
}
